# -*- coding: utf-8 -*-
"""hello.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19e1j960Dq3vP8wGQLxa0tbgcO9h06Xyy
"""

print("Hello from Binder!")

